### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by renanrdmachado** [renanrdmachado/WPAG#1]
# Checklist para sites Wordpress

## Setup
- [ ] Baixar e Instalar Wordpress
- [ ] Baixar e ativar o tema WPAG
- [ ] Definir quais as fontes que serão utilizadas

## Plugins
- [ ] Contact Form 7
- [ ] Mail Smtp
- [ ] Yoast SEO
- [ ] Advanced Custom Fields
- [ ] WP Smush
- [ ] [Whatsapp](https://github.com/renanrdmachado/Whatsapp)

## Finalização
- [ ] Revisão do Responsivo
- [ ] Revisão dos links de publicação (remover localhost)
- [ ] Alterar todos os formulários para o e-mail do cliente
- [ ] Ativar o YoastSEO para publicação
- [ ] Aplicar Google Tag Manager (ou tag do Analytics)
- [ ] Enviar backup do site final para o cliente

## Avisos
* Seguir a documentação oficial do Wordpress
